apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cop
spec:
  selector:
    app: {{ .Release.Name }}-cop
  ports:
    - protocol: TCP
      port: 8090
      targetPort: cop
      name: cop
