apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dc
  labels:
    k8s-app: {{ .Release.Name }}-dc
spec:
  type: NodePort
  ports:
  - name: dc
    port: 8080
    targetPort: dc
  selector:
    k8s-app: {{ .Release.Name }}-dc
    svc: {{ .Release.Name }}-dc
